# Generated by Django 6.0.2 on 2026-02-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cvmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
