# Generated by Django 6.0.2 on 2026-02-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_educationmodel_experiencemodel_resumemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='description',
            field=models.TextField(),
        ),
    ]
