# Generated by Django 6.0.2 on 2026-02-14 15:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_resumemodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('development', 'Development'), ('design', 'Design'), ('wordpress', 'WordPress'), ('other', 'Other')], default='development', max_length=50)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('project_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='subtitle',
            field=models.CharField(max_length=50),
        ),
    ]
