# Generated by Django 6.0.2 on 2026-02-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_portfoliomodel_alter_resumemodel_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='blog/')),
                ('title', models.CharField(max_length=255)),
                ('comments_count', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Recent Post', max_length=200)),
                ('subtitle', models.CharField(default='Elevate your brand', max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Blog Section Header',
            },
        ),
    ]
