# Generated by Django 6.0.2 on 2026-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_blogpost_blogsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Completed Work', max_length=200)),
                ('subtitle', models.CharField(default='Elevate your brand', max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
