# Generated by Django 6.0.2 on 2026-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Me', max_length=200)),
                ('subtitle', models.CharField(default='Get in Touch', max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
